language: python
# cache pip deps
cache: pip
# build matrix
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python test.py -v
